# TUGAS PERTEMUAN KELIMA (03/04/2023)

### 5.16 List 2 Dimensi

#### 5.16.1 Pendahuluan Materi List 2 Dimensi
List 2 dimensi pada umumnya adalah menempatkan sebuah list di dalam list. Penggambarannya seperti sebuah matrik.

#### 5.16.2 Contoh Latihan Materi List 2 Dimensi

In [1]:
#LATIHAN 1
#Menggunakan perintah print dan list 2 dimensi

print('--------------{Latihan 1a}--------------')
#saya ingin mengetahui hasil output matrik berikut
matrik_bilangan_cacah = [
        [0,1,2,3,4],
        [5,6,7,8,9],
        [10,11,12,13,14],
        [15,16,17,18,19]
]
print('matrik = ', matrik_bilangan_cacah)
#di python ketika di print terlihat outputnya seperti menjadi vektor dalam vektor
#padahal artinya adalah matrik, di python tidak terlihat bentuk matrik nya
print('')

print('--------------{Latihan 1b}--------------')
#saya ingin memanggil baris matriks yang ketiga
print(matrik_bilangan_cacah[2])
print(matrik_bilangan_cacah[3])
print(matrik_bilangan_cacah[-1])
#memperhatikan urutan
#urutan baris pertama dimulai dari index 0, maka ketika ingin memanggil baris ketiga matrik yang digunakan adalah [2] bukan [3]
#urutan terakhir adalah [-1]
print('')

print('--------------{Latihan 1c}--------------')
#saya mencoba memaggil baris dan kolom tertentu pada matrik
print(matrik_bilangan_cacah[1][4])
#artinya memanggil baris ke-2 kolom ke-5
print(matrik_bilangan_cacah[0][3])
#artinya memanggil baris ke-1 kolom ke-4
print(matrik_bilangan_cacah[3][1])
#artinya memanggil baris ke-4 kolom ke-2
print('')

print('--------------{Latihan 1d}--------------')
#saya ingin mencoba print baris ke-2 sampai baris terakhir akhir
print(matrik_bilangan_cacah[1:4])
#index [1:4] artinya akan di print baris kedua sampai baris kelima yaitu baris terakhir.
print('')

print('--------------{Latihan 1e}--------------')
#saya ingin mencoba mengganti nilai matrik
matrik_bilangan_cacah[1][2]=22
print(matrik_bilangan_cacah[1][2])
#saya coba dengan mengganti matrik baris kedua kolom ketiga
#misalnya matrik[1][2] diganti dengan 22, maka 7 diganti menjadi 22
#saya ingin coba lagi mengganti matrik baris keempat kolom kelima
matrik_bilangan_cacah[3][4]=20
print(matrik_bilangan_cacah[3][4])
#setelah di run, penggantian nilai matrik ini akan tersimpan dimemori
print('')

print('--------------{Latihan 1f}--------------')
print('matrik = ', matrik_bilangan_cacah)
#setelah di run akan terlihat pengaruh dari penggantian nilai matrik di 1e
print('')

--------------{Latihan 1a}--------------
matrik =  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]

--------------{Latihan 1b}--------------
[10, 11, 12, 13, 14]
[15, 16, 17, 18, 19]
[15, 16, 17, 18, 19]

--------------{Latihan 1c}--------------
9
3
16

--------------{Latihan 1d}--------------
[[5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]

--------------{Latihan 1e}--------------
22
20

--------------{Latihan 1f}--------------
matrik =  [[0, 1, 2, 3, 4], [5, 6, 22, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 20]]



In [3]:
#LATIHAN 2
#menggunakan perintah print, list 2 dimensi, for loop
#masih menggunakan parameter yang sama seperti LATIHAN 1

print('-------------------------------------------------------------------------------------------')
print('Contoh Latihan List 2 Dimensi yang Benar')
print('-------------------------------------------------------------------------------------------')
for baris in matrik_bilangan_cacah:
    print(baris)
    print(' ')
    #print pengulangan yang pertama akan tercetak baris masing-masing matrik
    for kolom in baris:
        print(kolom)
        print(' ')
        #print pengulangan yang kedua, akan diproses percetakan kolom di baris, jadi elemen-elemen kolomnya akan di print
        
#perhatikan for yang pertama dan for yang kedua memiliki arti yang beda
#jika for yang kedua diletakkan sejajar dengan for yang pertama maka tidak akan tercetak elemen-elemen kolomnya, karena yang diproses adalah 'baris in matriik'
print('-------------------------------------------------------------------------------------------')
print('Contoh Kesalahan Kode List 2 Dimensi karena Kesalahan Penempatan perintah pengulangan/for')
print('-------------------------------------------------------------------------------------------')
#coba buat for yang kedua sejajar dengan for pertama
for baris in matrik_bilangan_cacah:
    print(baris)
for kolom in baris:
        print(kolom)
#setelah di run hasilnya berbeda, dan tidak beraturan

-------------------------------------------------------------------------------------------
Contoh Latihan List 2 Dimensi yang Benar
-------------------------------------------------------------------------------------------
[0, 1, 2, 3, 4]
 
0
 
1
 
2
 
3
 
4
 
[5, 6, 22, 8, 9]
 
5
 
6
 
22
 
8
 
9
 
[10, 11, 12, 13, 14]
 
10
 
11
 
12
 
13
 
14
 
[15, 16, 17, 18, 20]
 
15
 
16
 
17
 
18
 
20
 
-------------------------------------------------------------------------------------------
Contoh Kesalahan Kode List 2 Dimensi karena Kesalahan Penempatan perintah pengulangan/for
-------------------------------------------------------------------------------------------
[0, 1, 2, 3, 4]
[5, 6, 22, 8, 9]
[10, 11, 12, 13, 14]
[15, 16, 17, 18, 20]
15
16
17
18
20


### 5.17 Tuples 

#### 5.17.1 Pendahuluan Materi Tuples
Tuples mirip dengan list, akan tetapi tuples tidak dapat dirubah isinya. Jika kita memiliki data yang tidak ingin dirubah isinya, kita gunakan tuples, sedangkan jika datanya masih ingin dimanipulasi kedepannya, gunakan list.

#### 5.17.2 Contoh Latihan Materi Tuples

In [60]:
#lATIHAN 1
#menggunakan perintah print, tuples, for loop

#tuple tidak bisa dirubah
print('--------------{Latihan 1a}--------------')
#saya ingin menggunakan nama akhir saya sebagai objek dari tuples
NAMA_AKHIR_018 = ('A','N','T','A','R','I')
print('Nama Akhir NIM 018 adalah ', NAMA_AKHIR_018)
print(' ')

print('--------------{Latihan 1b}--------------')
#saya mencoba print masing-masing objek tuples
#saya kan print menjadi 1 kolom
print(NAMA_AKHIR_018[0])
#urutan ke-0 dalam 'NAMA_AKHIR_018' adalah 'A'
print(NAMA_AKHIR_018[1])
#urutan ke-1 dalam 'NAMA_AKHIR_018' adalah 'N'
print(NAMA_AKHIR_018[2])
#urutan ke-2 dalam 'NAMA_AKHIR_018' adalah 'T'
print(NAMA_AKHIR_018[3])
#urutan ke-3 dalam 'NAMA_AKHIR_018' adalah 'A'
print(NAMA_AKHIR_018[4])
#urutan ke-4 dalam 'NAMA_AKHIR_018' adalah 'R'
print(NAMA_AKHIR_018[-1])
#urutan terakhir dalam 'NAMA_AKHIR_018' adalah 'I'
print(' ')

print('--------------{Latihan 1c}--------------')
#saya coba print objek tertentu dengan bantuan for loop
print(NAMA_AKHIR_018[0:3])
for isi in NAMA_AKHIR_018[0:3]:
    print(isi)
#akan diprint isi dari huruf ke-1 sampai huruf ke-3
print(' ')

print('--------------{Latihan 1d}--------------')
#saya ingin menghitung jumlah huruf tertentu yang ada dalam NAMA_AKHIR-018
#count untuk menghitung jumlah angka
print('Jumlah huruf A dalam NAMA_AKHIR_018 adalah ', NAMA_AKHIR_018.count('A'), 'huruf')
#jumlah huruf A ada 2 (bisa dicek lagi kebenarannya saat sudah di run)
#coba lagi
print('Jumlah huruf T dalam NAMA_AKHIR_018 adalah ', NAMA_AKHIR_018.count('T'), 'huruf')
#coba lagi
print('Jumlah huruf I dalam NAMA_AKHIR_018 adalah ', NAMA_AKHIR_018.count('I'), 'huruf')
print(' ')

print('--------------{Latihan 1e}--------------')
#saya ingin mengetahui index dari huruf tertentu yang saya inginkan
print('index A adalah ', NAMA_AKHIR_018.index('A'))
#yang disebutkan adalah objeknya yaitu 'A'
#'A' adalah urutan huruf pertama
#index nya adalah 0, maka setelah di run terlihat index dari 'N'
#coba lagi
print('index R adalah ', NAMA_AKHIR_018.index('R'))
#coba lagi
print('index I adalah ', NAMA_AKHIR_018.index('I'))

#PENTING!!!
#tadinya saya sempat mencoba mengganti, menghapus dan menambahkan objek tapi tidak bisa. Ternyata saya lupa bahwa tuples berbeda dengan list yang objeknya bisa diganti dan ditambahkan, tapi ini tidak berlaku di tuples. Objek di tuples tidak bisa diganti ataupun ditambahkan.

--------------{Latihan 1a}--------------
Nama Akhir NIM 018 adalah  ('A', 'N', 'T', 'A', 'R', 'I')
 
--------------{Latihan 1b}--------------
A
N
T
A
R
I
 
--------------{Latihan 1c}--------------
('A', 'N', 'T')
A
N
T
 
--------------{Latihan 1d}--------------
Jumlah huruf A dalam NAMA_AKHIR_018 adalah  2 huruf
Jumlah huruf T dalam NAMA_AKHIR_018 adalah  1 huruf
Jumlah huruf I dalam NAMA_AKHIR_018 adalah  1 huruf
 
--------------{Latihan 1e}--------------
index A adalah  0
index R adalah  4
index I adalah  5


### 5.18 Dictionaries

#### 5.18.1 Pendahuluan Materi Dictionaries
Dictionaries digunakan jika data nya terkait satu sama lain. Misalnya data seseorang yang terdiri dari umur, nama, tanggal lahir merupakan satu kesatuan data yang bersumber dari orang tersebut. 

#### 5.18.2 Contoh Latihan Materi Dictionaries

In [17]:
#LATIHAN 1
#menggunakan perintah print dan dictionaries

print('--------------{Latihan 1a}--------------')
#saya menggunakan data yang bersumber hanya dari 1 orang, yaitu saya sendiri
DATA_MAHASISWA_018 = {
    "Nama" : "Ni Kadek Yuni Antari",
    "NIM" : 2208541018,
    "Kelas" : "A",
    "Jurusan" : "Matematika",
    "Umur" : 19,
    "Gender" : "Perempuan",
    "Alamat" : "Kuta"
}
#jangan lupa tanda koma (perhatikan lihat di dalam data), jangan sampai terluppa
print(DATA_MAHASISWA_018)
print('')

print('--------------{Latihan 1b}--------------')
#saya akan memanggil beberapa data
print(DATA_MAHASISWA_018['Nama'])
print(DATA_MAHASISWA_018['Gender'])
print(DATA_MAHASISWA_018['Umur'])
print(DATA_MAHASISWA_018['Alamat'])
print('')

print('--------------{Latihan 1c}--------------')
#saya ingin bercerita dan akan memanggil beberapa data
print('Nama saya adalah ', DATA_MAHASISWA_018['Nama'])
#saat saya memanggil 'nama' akan terjadi error, karena python sangat sensitive meskipun hanya perbedaan huruf kapital atau tidak akan menyebabkan error
print('NIM saya adalah ', DATA_MAHASISWA_018['NIM'])
print('Saya kuliah di Universitas Udayana dan mengambil Jurusan', DATA_MAHASISWA_018['Jurusan'])
print('')

print('--------------{Latihan 1d}--------------')
#perhatikan penggunaan huruf kapital dan huruf kecil berikut pada kata "Nama"
print(DATA_MAHASISWA_018.get('Nama'))
print(DATA_MAHASISWA_018.get('nama'))
#kata "Nama" benar adanya pada data
#tetapi kata "nama" tidak benar, maka nantinya hasil outputnya akan bertuliskan "None"
print('')

print('--------------{Latihan 1e}--------------')
#saya coba ingin menambahkan data agar tersimpan di memori, tapi ternyata caranya salah
print(DATA_MAHASISWA_018.get('tanggal_lahir', '22 Juni'))
#tidak merubah elemen dari DATA_MAHASISWA_018, hanya menambahkan saja tapi tidak merubah matrik
#seharusnya jika ingin menambahkan data ke, cara yang benar adalah sebagai berikut
DATA_MAHASISWA_018['Tanggal_lahir'] = '22 Juni'
#sehingga tidak akan menyebabkan error, dan data tersimpan di memori
DATA_MAHASISWA_018['Tahun_lahir'] = '2003'
print(DATA_MAHASISWA_018['Tahun_lahir'])
print('')
print('tanggal lahir saya adalah ', DATA_MAHASISWA_018["Tanggal_lahir"], DATA_MAHASISWA_018["Tahun_lahir"])
print('')

print('--------------{Latihan 1f}--------------')
#saya ingin print semua data yang saya pakai
print(DATA_MAHASISWA_018)

--------------{Latihan 1a}--------------
{'Nama': 'Ni Kadek Yuni Antari', 'NIM': 2208541018, 'Kelas': 'A', 'Jurusan': 'Matematika', 'Umur': 19, 'Gender': 'Perempuan', 'Alamat': 'Kuta'}

--------------{Latihan 1b}--------------
Ni Kadek Yuni Antari
Perempuan
19
Kuta

--------------{Latihan 1c}--------------
Nama saya adalah  Ni Kadek Yuni Antari
NIM saya adalah  2208541018
Saya kuliah di Universitas Udayana dan mengambil Jurusan Matematika

--------------{Latihan 1d}--------------
Ni Kadek Yuni Antari
None

--------------{Latihan 1e}--------------
22 Juni
2003

tanggal lahir saya adalah  22 Juni 2003

--------------{Latihan 1f}--------------
{'Nama': 'Ni Kadek Yuni Antari', 'NIM': 2208541018, 'Kelas': 'A', 'Jurusan': 'Matematika', 'Umur': 19, 'Gender': 'Perempuan', 'Alamat': 'Kuta', 'Tanggal_lahir': '22 Juni', 'Tahun_lahir': '2003'}


In [1]:
#LATIHAN 2
#menggunakan perintah print, input, for loop, Dictionaries, operasi matematika pada python

#saya ingin membuat output berupa NIM dan diterjemahkan dengan kata-kata
#masukkan dulu data-datanya yang berupa angka yang nantinya akan digunakan sebagai input NIM
angka = {
    "0" : "Nol",
    "1" : "Satu",
    "2" : "Dua",
    "3" : "Tiga",
    "4" : "Empat",
    "5" : "Lima",
    "6" : "Enam",
    "7" : "Tujuh",
    "8" : "Delapan",
    "9" : "Sembilan"
}
nama_mahasiswa = input("Siapakah nama Anda? ")
kelas_mahasiswa = input("Anda kelas apa? " )
nomor_NIM = input("Berapakah NIM Anda? ")
#saya gunakan perintah input agar bebas bisa memasukkan NIM berapa
nomor_angka = ""
for isi in nomor_NIM:
    nomor_angka += angka.get(isi) + " "
    # tanda += untuk menambahkan setiap kata angka seperti yang diisikan diinput
    # + " " untuk menambahkan spasi agar ada jarak di setiap kata
    # misalnya 01 maka 'nol' + " " + 'satu' = nol satu
print('Ejaan NIM = ', nomor_angka)
print('---------------------------------------------------')
print('Selamat datang mahasiswa baru angkatan 2022 dengan NIM ',nomor_NIM,'(',nomor_angka,')', 'atas nama ', nama_mahasiswa, 'di Prodi Matematika Universitas Udayana, Anda mendapatkan kelas', kelas_mahasiswa)

Siapakah nama Anda? Ni Kadek Yuni Antari
Anda kelas apa? A
Berapakah NIM Anda? 2208541018
Ejaan NIM =  Dua Dua Nol Delapan Lima Empat Satu Nol Satu Delapan 
---------------------------------------------------
Selamat datang mahasiswa baru angkatan 2022 dengan NIM  2208541018 ( Dua Dua Nol Delapan Lima Empat Satu Nol Satu Delapan  ) atas nama  Ni Kadek Yuni Antari di Prodi Matematika Universitas Udayana, Anda mendapatkan kelas A


### 5.19 Fungsi dalam Python

#### 5.19.1 Pendahuluan Materi Fungsi dalam Python
Sampai sejauh ini tanpa disadari kita telah menerapkan beberapa jenis fungsi pada Python seperti fungsi input, print, len, range, dll. Pada dasarnya fungsi dibentuk untuk menghidari pengulangan pembuatan program secara manual dimana fungsi tersebut memiliki pengulangan yang tinggi dalam program yang kita buat. Jadi untuk mempermudah dan meringkas program yang kita buat, setiap fungsi tersebut dibutuhkan tinggal kita panggil.

#### 5.19.2 Tugas Fungsi pada Python
Ada dua jenis tugas fungsi pada Python yaitu:
1. Menjalankan perintah.
2. Menampilkan hasil perhitungan.

#### 5.19.3 Contoh Latihan Materi Fungsi dalam Python
Untuk lebih jelas mengenai perbedaan kedua tugas tersebut dapat dilihat pada LATIHAN 1

In [24]:
#LATIHAN 1
#materi fungsi dalam python

#jenis fungsi pada python untuk menjalankan perintah
def waktu_sampai(jarak,kecepatan):
    waktu = jarak/kecepatan
    return(waktu)
def waktu_tempuh(jarak,kecepatan):
    waktu = jarak/kecepatan
    return(waktu)
#jenis fungsi pada python untuk menampilkan hasil perhitungan
a = waktu_sampai(100,60)
print('waktu sampai adalah ', a, 'jam' )
b = waktu_tempuh(100,60)
print('waktu tempuh adalah', b, 'jam')

waktu sampai adalah  1.6666666666666667 jam
waktu tempuh adalah 1.6666666666666667 jam


In [27]:
#LATIHAN 2
#materi fungsi dalam python dipadukan dengan perintah print dan input

#mencoba membuat fungsi untuk nama lengkap seseorang
def full_nama(first_name,last_name):
    print(f"Nama lengkapnya adalah {first_name} {last_name}")

first_name = input("Nama depan anda adalah ")
last_name = input("Nama belakang anda adalah ")
full_nama(first_name, last_name)

Nama depan anda adalah Yuni
Nama belakang anda adalah Antari
Nama lengkapnya adalah Yuni Antari


In [17]:
#LATIHAN 3
#materi fungsi dalam python
#mencoba menghitung luas bangun datar dan volume bangun ruang

#menghitung luas bangun datar persegi
print('-----------------------------{Latihan 1a}-----------------------------')
print('Hitunglah luas persegi panjang yang memiliki panjang 10 cm dan lebar 6 cm!')
def luas_persegi_panjang(panjang,lebar):
    luas = panjang*lebar
    return(luas)
a = luas_persegi_panjang(10,6)
print('')
print('luas persegi panjang adalah', a, 'cm^2')
print('')

#mencoba lagi menghitung luas bangun datar segitiga
print('-----------------------------{Latihan 1b}-----------------------------')
print('Hitunglah luas segitiga yang memiliki tinggi 12 cm dan alas 6 cm!')
def luas_segitiga(alas,tinggi):
    luas = 1/2*alas*tinggi
    return(luas)
a = luas_segitiga(12,6)
print('')
print('luas segitiga adalah', a, 'cm^2')
print('')

#mencoba menghitung volume balok
print('-----------------------------{Latihan 1c}-----------------------------')
print('Hitunglah volume balok yang memiliki panjang 10 cm, lebar 8 cm, dan tinggi 4 cm!')
def volume_balok(panjang,lebar,tinggi):
    volume = panjang*lebar*tinggi
    return(volume)
a = volume_balok(10,8,4)
print('')
print('volume balok adalah adalah', a, 'cm^3')
print('')

#mencoba menghitung volume balok
print('-----------------------------{Latihan 1d}-----------------------------')
print('Hitunglah volume kubus yang memiliki panjang rusuk 6 cm!')
def volume_kubus(rusuk):
    volume = rusuk**3
    return(volume)
a = volume_kubus(6)
print('')
print('volume kubus adalah adalah', a, 'cm^3')
print('')

-----------------------------{Latihan 1a}-----------------------------
Hitunglah luas persegi panjang yang memiliki panjang 10 cm dan lebar 6 cm!

luas persegi panjang adalah 60 cm^2

-----------------------------{Latihan 1b}-----------------------------
Hitunglah luas segitiga yang memiliki tinggi 12 cm dan alas 6 cm!

luas segitiga adalah 36.0 cm^2

-----------------------------{Latihan 1c}-----------------------------
Hitunglah volume balok yang memiliki panjang 10 cm, lebar 8 cm, dan tinggi 4 cm!

volume balok adalah adalah 320 cm^3

-----------------------------{Latihan 1d}-----------------------------
Hitunglah volume kubus yang memiliki panjang rusuk 6 cm!

volume kubus adalah adalah 216 cm^3



### 5.20 Numpy

#### 5.20.1 Pendahuluan Materi Numpy
Numpy merupakan salah satu Library dalam Python yang memiliki keunggulan dalam perhitungan menggunakan vektor dam matrik dalam berbagai dimensi.Hal pertama yang perlu dilakukan adalah memanggil Library Numpy sebagai berikut:

In [19]:
import numpy as np

#### 5.20.2 Contoh Latihan Perintah Dasar pada Numpy
Perintah dalam Numpy diantaranya: memanggil Numpy, mengetahui dimensi dan ukuran variabel.

In [30]:
#latihan perintah dasar numpy

print('------------------------{Latihan 1}-----------------------------')
#langkah pertama adalah mengimpor mengimpor library numpy yaitu 'np'
#np.array adalah fungsi untuk menyimpan variabel
print('contoh data array dengan matrik ordo 2x5')
a = np.array([[0,1,2,3,4], [5,6,7,8,9]])
print(a)
print('')
print('contoh data array dengan matrik ordo 2x4')
b = np.array([[5,6,7,8],[9,8,7,6],[11,12,13,14]])
print(b)
print('')
print('contoh himpunan data array dengan ordo masing-masing matrik 2x4')
c = np.array([[[0,1,2,3],[4,5,6,7]], 
              [[8,9,8,7],[6,5,4,3]],
              [[1,2,3,4],[5,6,7,8]]])
print(c)
print('')

print('------------------------{Latihan 2}-----------------------------')
#masih menggunakan data array yang sama seperti Latihan 1
# .ndim digunakan untuk mengetahui dimensi dari sebuah array
#sebenarnya bisa dilihat dari ada berapa banyak pasang kurung sikunya
print(a.ndim)
print(b.ndim)
print(c.ndim)
print('')

print('------------------------{Latihan 3}-----------------------------')
#masih menggunakan data array yang sama seperti Latihan 1
# .shape digunakan untuk mengetahui jumlah baris dan jumlah kolom
print(a.shape)
# jumlah elemen baris ada 2, dan jumlah kolom ada 5 jadi hasilnya (2,5)
print(b.shape)
# jumlah elemen baris ada 3, dan jumlah kolom ada 4 jadi hasilnya (3,4)
print(c.shape)
# ada 3 himpunan matrik dengan masing-masing barisnya 2 dan kolomnya 4, sehingga hasilnya (3,2,4)

------------------------{Latihan 1}-----------------------------
contoh data array dengan matrik ordo 2x5
[[0 1 2 3 4]
 [5 6 7 8 9]]

contoh data array dengan matrik ordo 2x4
[[ 5  6  7  8]
 [ 9  8  7  6]
 [11 12 13 14]]

contoh himpunan data array dengan ordo masing-masing matrik 2x4
[[[0 1 2 3]
  [4 5 6 7]]

 [[8 9 8 7]
  [6 5 4 3]]

 [[1 2 3 4]
  [5 6 7 8]]]

------------------------{Latihan 2}-----------------------------
2
2
3

------------------------{Latihan 3}-----------------------------
(2, 5)
(3, 4)
(3, 2, 4)


#### 5.20.3  Contoh Latihan Memanggil Anggota, Kolom dan Baris dengan Numpy
Program memanggil anggota, kolom dan baris dalam list menggunakan Numpy, untuk lebih jelasnya dapat dilihat dari contoh latihan berikut.

In [39]:
#Latihan memanggil anggota, kolom dan baris dengan numpy

print('------------------------{Latihan 1}-----------------------------')
#mencetak sebuah data array berupa matrik
#langkah pertama adalah mengimpor mengimpor library numpy yaitu 'np'
Y = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#cetak Y
print(Y)
print('')

print('------------------------{Latihan 2}-----------------------------')
#memanggil anggota,kolom,dan baris tertentu
print (Y[0,3])
#memanggil baris urutan ke-0 dan kolom urutan ke 3
#perhatikan baris urutan ke-0 maksudnya adalah baris ke-1 dan kolom urutan ke-3 artinya kolom ke-4
print('')
print (Y[1,:])
#memanggil baris ke-2 dan semua kolom di baris ke-2
print('')
print (Y[:,2])
#memanggil kolom ke-3 dan semua baris di kolom ke-3
print('')
print (Y[0,1:3])
#memanggil baris ke-1, kolom ke-2 dan kolom ke-3
print('')
print (Y[0,0:3:2])
#memanggil baris ke 1, kolom ke-1, ke-3
print('')
Y[0,0] = 100
#mengganti baris ke-1, kolom ke-1 dengan 100
print(Y)
#cetak hasilnya

------------------------{Latihan 1}-----------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

------------------------{Latihan 2}-----------------------------
4

[5 6 7 8]

[ 3  7 11]

[2 3]

[1 3]

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


#### 5.20.4 Contoh Latihan Matrix pada Numpy
Numpy dapat digunakan untuk membuat berbagai jenis matrix.

In [41]:
#LATIHAN 1 SAMPAI LATIHAN 7
#Latihan Matrix pada Numpy

print('------------------------{Latihan 1}-----------------------------')
#np.ones adalah digunakan untuk mencetak sebuah matrik dengan ordo tertentu yang semua elemennya adalah 1
print(np.ones((2,3)))
#akan dicetak matrik ordo 2x3 yang semua elemennya adalah 1
print('')

print('------------------------{Latihan 2}-----------------------------')
#np.zeros adalah digunakan untuk mencetak sebuah matrik dengan ordo tertentu yang semua elemennya adalah 0
print(np.zeros((3,2)))
#akan dicetak matrik ordo 3x2 yang semua elemennya adalah 0
print('')

print('------------------------{Latihan 3}-----------------------------')
#np.identity adalah digunakan untuk mencetak sebuah matrik dengan ordo tertentu yang semua elemennya adalah matrik identitas
print(np.identity(4))
#akan dicetak ssebuah matrik identitas dengan ordo 4x4
print('')

print('------------------------{Latihan 4}-----------------------------')
print(np.ones((2,3,4)))
#mencetak 2 himpunan matrik ordo 3x4 yang semua elemennya adalah 1
print('')

print('------------------------{Latihan 5}-----------------------------')
print(np.full((3,2),9))
#mencetak matrik ordo 3x2 yang semua elemennya adalah 9
print('')

print('------------------------{Latihan 6}-----------------------------')
print(np.random.rand(4,3))
#menghasilkan matrik ordo 4x3 dengan nilai yang random/acak yang terdistribusi seragam
print('')

print('------------------------{Latihan 7}-----------------------------')

print(np.random.randint(1,10,size=(3,4)))
#mencetak matrik dengan ukuran ordo 3x4 dan elemen-elemennya adalah antara 1 sampai 10, yaitu dari 2 sampai 9, elemen-elemen tersebut ditempatkan acak
print('')

------------------------{Latihan 1}-----------------------------
[[1. 1. 1.]
 [1. 1. 1.]]

------------------------{Latihan 2}-----------------------------
[[0. 0.]
 [0. 0.]
 [0. 0.]]

------------------------{Latihan 3}-----------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

------------------------{Latihan 4}-----------------------------
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

------------------------{Latihan 5}-----------------------------
[[9 9]
 [9 9]
 [9 9]]

------------------------{Latihan 6}-----------------------------
[[0.23236494 0.31258372 0.30977392]
 [0.96113557 0.69856188 0.2849284 ]
 [0.3029688  0.22046913 0.05853778]
 [0.16163373 0.97818202 0.05696268]]

------------------------{Latihan 7}-----------------------------
[[8 7 9 3]
 [8 7 1 2]
 [3 1 5 7]]



In [45]:
#LATIHAN 8 SAMPAI 17
#Latihan pada numpy dengan perintah print dan operasi matematika dalam python

print('------------------------{Latihan 8}-----------------------------')
a = np.zeros((10,10))
#akan dicetak matrik ordo 10x10 dengan semua elemennya adalah 0
print(a)
print('')

print('------------------------{Latihan 9}-----------------------------')
b = np.identity(10)
#akan dicetak matrik ordo 10x10 dengan elemennya adalah elemen identitas
print(b)
print('')

print('------------------------{Latihan 10}-----------------------------')
c = 9*b
#akan dicetak matrik seperti matrik b (pada latihan 9), tapi angka elemen identitas yaitu 1 diganti dengan 9
print(c)
print('')

print('------------------------{Latihan 11}-----------------------------')
d = np.ones((8,8))
e = np.identity(8)*8
f = d+e
#akan dicetak matriks orde 8x8 yang semua elemennya 1
#tapi pada diagonal utama nilainya diganti menjadi 8
print(f)
print('')

print('------------------------{Latihan 12}-----------------------------')
c[1:-1,1:-1] = f
#cetak matrik c, tapi di elemen terluar (tidak termasuk diagonal utama) diganti jadi 0
print(c)
print('')

print('------------------------{Latihan 13}-----------------------------')
g = np.identity(6)*9
c[2:-2,2:-2] = g
#sedikit susah dijelaskan menggunakan kata, untuk lebih jelas bisa langsung dilihat ke hasil output
print(c)
print('')

print('------------------------{Latihan 14}-----------------------------')
c[3:-3, 3:-3] = j
print(c)
#susah dijelaskan menggunakan kata, untuk lebih jelas bisa langsung dilihat ke hasil output
print('')

print('------------------------{Latihan 15}-----------------------------')
k = np.identity(2)*9
c[4:-4,4:-4] = k
#sedikit susah dijelaskan menggunakan kata, untuk lebih jelas bisa langsung dilihat ke hasil output
print(c)

------------------------{Latihan 8}-----------------------------
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

------------------------{Latihan 9}-----------------------------
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

------------------------{Latihan 10}-----------------------------
[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 9. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 9. 0. 0. 0. 0. 0. 0.]
 [0. 0. 

#### 5.20.5 Contoh Latihan Copy pada Numpy
Sering sekali kita menduplikat suatu variabel dengan maksud untuk mempercepat pekerjaan kita. Akan tetapi sering tanpa disadari ikatan persamaan dalam Numpy sedemikian eratnya sehingga saat anggota variabel baru dirubah, dampaknya juga akan merubah variabel asal. Untuk menghindari perubahan variabel awal yang tidak dikehendaki maka diperlukan perintah copy.

In [49]:
#LATIHAN 1
#berikut adalah contoh latihan copy pada numpy

#deklarasikan matrik a dengan numpy
a = np.array([1,2,3,4,5,6,7])
print(a)
#copy matrik a sebagai matrik b
b = a
print(b)
#ganti urutan ke-0 matrik dengan 10
b[0] = 10
print(b)
#cetak a yang nilainya sama seperti b
print(a)

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[10  2  3  4  5  6  7]
[10  2  3  4  5  6  7]


In [53]:
#LATIHAN 2
#berikut adalah contoh latihan copy pada numpy
#mirip seperti LATIHAN 1

#deklarasikan data array dengan matrik
c = np.array([1,2,3,4,5,6,7])
#cetak matrik c
print(c)
#berikut cara copy matrik c menjadi d
d = c.copy()
print(d)
#ganti urutan ke-0 dengan 10
d[0] = 10
print(d)
print(c)
#cetak d dan c yang memiliki elemen yang sama
#bandingkan dengan LATIHAN 1, ternyata hasil outputnya akan sama seperti LATIHAN 1

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[10  2  3  4  5  6  7]
[1 2 3 4 5 6 7]


#### 5.20.6 Contoh Latihan Operasi Matematika pada Numpy
Ada beberapa operasi matematika pada Numpy, untuk lebih jelasnya bisa dilihat pada contoh latihan berikut.

In [2]:
import numpy as np

In [12]:
#LATIHAN 1 SAMPAI LATIHAN 3
#Latihan operasi matematika pada numpy

#dalam mengoperasikan matrik usahakan orde atau ukuran matrik nya sama
#saya mencoba menggunakan ukuran matrik yang berbeda tetapi yang terjadi error saat di run
print('------------------------{Latihan 1}-----------------------------')
a = np.array([1,2,3,4,5])
print(a+1)
print(a-1)
print(a*1)
print(a/2)
print(a**1)
print('')
print('------------------------{Latihan 2}-----------------------------')
b = np.array([6,7,8,9,10])
print(b)
#operasikan dengan matrik b pada Latihan 1
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print('')
print('')
print(b**a)
print('')
print('------------------------{Latihan 3}-----------------------------')
#coba dengan operasikan dengan  operasi trigonometri
print('')
print(np.cos(a))
print('')
print(np.tan(a))
print('')
print(np.sinh(a))
print('')
print(np.cosh(a))
print('')
print(np.tanh(a))
print('')
print(np.sqrt(a))
#jangan lupa gunakan perintah print agar outputnya terlihat

------------------------{Latihan 1}-----------------------------
[2 3 4 5 6]
[0 1 2 3 4]
[1 2 3 4 5]
[0.5 1.  1.5 2.  2.5]
[1 2 3 4 5]

------------------------{Latihan 2}-----------------------------
[ 6  7  8  9 10]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


[     6     49    512   6561 100000]

------------------------{Latihan 3}-----------------------------

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]

[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]

[ 1.17520119  3.62686041 10.01787493 27.2899172  74.20321058]

[ 1.54308063  3.76219569 10.067662   27.30823284 74.20994852]

[0.76159416 0.96402758 0.99505475 0.9993293  0.9999092 ]

[1.         1.41421356 1.73205081 2.         2.23606798]


#### 5.20.7 Contoh Latihan  Perkalian Matrik pada Numpy
Dapat diamati bahwa operasi matematika pada suatu matrik dengan Numpy akan mengoperaikan elemen yang baris dan kolomnya sama. Tentunya hal ini akan memberikan hasil berbeda jika yang kita kehendaki adalah perkalian dua matrik. Perkalian matrik pada Numpy dapat menggunakan perintah matmul. Perlu dijadikan perhatian tentang ukuran matrik yang akan dikalikan harus sesuai dengan persyaratan. Misalnya matrik ukuran (2x3) dapat dikalikan dengan matrik ukuran (3x4).

In [14]:
import numpy as np

In [24]:
#LATIHAN 1
#Latihan perkalian matik pada numpy

#deklarasikan matrik a dan b, lalu cetak
print('matrik a = ')
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print('-------------------------------------------')
print('matrik b = ')
b = np.array([[9,10,11,12], [13,14,15,16]])
print(b)
print('-------------------------------------------')
#coba kalikan matrik a dan b, sehingga hasilnya akan menjadi matrik c
print('matrik c = ')
c = a*b
print(c)
print('-------------------------------------------')
#deklarasikan sebuah matrik e
print('matrik e = ')
e = np.array([[9,10], [11,12], [13,14], [15,16]])
print(e)
print('-------------------------------------------')
print('matrik f = ')
f = np.matmul(a,e)
# .matmul untuk perkalian matrik 2 matrik, yaitu matrik a dan e
print(f)
print('-------------------------------------------')
print('matrik g = ')
g = a*b
#perkalian matrik juga bisa langsung menggunakan tanda * tapi pada numpy menggunakan np.malmut
print(g)

matrik a = 
[[1 2 3 4]
 [5 6 7 8]]
-------------------------------------------
matrik b = 
[[ 9 10 11 12]
 [13 14 15 16]]
-------------------------------------------
matrik c = 
[[  9  20  33  48]
 [ 65  84 105 128]]
-------------------------------------------
matrik e = 
[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]
-------------------------------------------
matrik f = 
[[130 140]
 [322 348]]
-------------------------------------------
matrik g = 
[[  9  20  33  48]
 [ 65  84 105 128]]


#### 5.20.8 min, max, dan sum pada Numpy
Perintah min, max dan sum cukup sering digunakan untuk mengetahui nilai minimum, maksimum dan penjumlahan

In [25]:
import numpy as np

In [42]:
#LATIHAN 1
#latihan menggunakan perintah min, max, dan sum pada numpy

#deklarasikan data array dengan matrik
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
#'------------------Menggunakan Perintah Min---------------------'
print('matrik a = ')
print(a)
print('')
print('nilai min = ')
#nilai minimal di matrik a
b = np.min(a)
print(b)
print('')
print('nilai min matrik a,axis=0')
c = np.min(a,axis=0)
print(c)
print('')
print('nilai min matrik a,axis=1')
d = np.min(a,axis=1)
print(d)
print('')

matrik a = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

nilai min = 
1

nilai min matrik a,axis=0
[1 2 3 4]

nilai min matrik a,axis=1
[1 5 9]



In [45]:
#LATIHAN 2
#latihan menggunakan perintah min, max, dan sum pada numpy
#masih berhubungan dengan LATIHAN 1

#'------------------Menggunakan Perintah Max---------------------'
print('nilai max = ')
e = np.max(a)
#nilai maksimal di matrik a (pada LATIHAN 1)
print(e)
print('')
print('nilai max a,axis=0 ')
f = np.max(a,axis=0)
print(f)
print('')
print('nilai max a,axis=1 ')
g = np.max(a,axis=1)
print(g)
print('')

nilai max = 
12

nilai max a,axis=0 
[ 9 10 11 12]

nilai max a,axis=1 
[ 4  8 12]



In [47]:
#LATIHAN 3
#latihan menggunakan perintah min, max, dan sum pada numpy
#Masih berhubungan dengan LATIHAN 1

#'------------------Menggunakan Perintah Sum---------------------'
print('nilai sum = ')
h = np.sum(a)
#semua elemen ditambahkan
print(h)
print('')
print('nilai sum a,axis=0 ')
h = np.sum(a,axis=0)
print(h)
print('')
print('nilai sum a,axis=1 ')
i = np.sum(a,axis=1)
print(i)

nilai sum = 
78

nilai sum a,axis=0 
[15 18 21 24]

nilai sum a,axis=1 
[10 26 42]


# *** Terima Kasih ***